"""
Generate .def files from DT_ConstructionRecipes.json and DT_Constructions.json

This helper script creates individual .def files for each construction,
combining the recipe and construction data in proper XML format.
The JSON objects are embedded exactly as they appear in the source files.

Key structure:
- NameMap: Auto-generated by UAssetAPI (NOT stored in .def files)
- Imports: Icon texture references for DT_Constructions (stored in .def files)
- Data: The actual row content (stored in .def files via CDATA)

Usage:
    python helpers/generate_building_defs.py

Output:
    %AppData%/MoriaMODCreator/Definitions/Building/New Objects/*.def
"""

import json
import html
import os
from pathlib import Path
from typing import Optional


def get_output_dir() -> Path:
    """Get the output directory in AppData."""
    appdata = os.environ.get('APPDATA')
    if not appdata:
        appdata = Path.home() / 'AppData' / 'Roaming'
    output_dir = Path(appdata) / 'MoriaMODCreator' / 'Definitions' / 'Building' / 'New Objects'
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def load_json_file(filepath: str) -> dict:
    """Load and parse a JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)


def escape_xml_value(value: str) -> str:
    """Escape special characters for XML attribute values."""
    return html.escape(value, quote=True)


def get_icon_import_index(construction_item: dict) -> Optional[int]:
    """Extract the Icon import index from a construction item.
    
    Icon property uses negative indices to reference Imports array.
    e.g., -2 means Imports[abs(-2) - 1] = Imports[1]
    """
    for prop in construction_item.get('Value', []):
        if prop.get('Name') == 'Icon':
            value = prop.get('Value')
            if isinstance(value, int) and value < 0:
                return value
    return None


def get_import_entries_for_icon(icon_index: int, all_imports: list) -> list:
    """Get the Import entries for an icon reference.
    
    Each icon typically needs 2 Import entries:
    - The Package entry (path to the icon asset)
    - The Texture2D entry (the actual texture reference)
    
    Icon index is negative, e.g., -2 means Imports[1] and we also need Imports[0]
    """
    if icon_index >= 0:
        return []
    
    # Convert negative index to array index
    # -2 → index 1, -4 → index 3, etc.
    texture_idx = abs(icon_index) - 1
    package_idx = texture_idx - 1
    
    result = []
    if 0 <= package_idx < len(all_imports):
        result.append(all_imports[package_idx])
    if 0 <= texture_idx < len(all_imports):
        result.append(all_imports[texture_idx])
    
    return result


def generate_def_file(
    construction_name: str,
    recipe_item: dict,
    construction_item: dict,
    icon_imports: list,
    output_dir: Path
) -> Path:
    """Generate a .def file for a single construction in proper XML format.
    
    Args:
        construction_name: The name of the construction
        recipe_item: The recipe JSON object from DT_ConstructionRecipes
        construction_item: The construction JSON object from DT_Constructions
        icon_imports: The Import entries for the icon (for DT_Constructions)
        output_dir: Directory to write the .def file
    """
    
    # Serialize the JSON objects exactly as they appear
    recipe_json = json.dumps(recipe_item, separators=(',', ':'))
    construction_json = json.dumps(construction_item, separators=(',', ':'))
    
    # Serialize imports if present
    imports_section = ""
    if icon_imports:
        imports_json = json.dumps(icon_imports, separators=(',', ':'))
        imports_section = f'''
    <add_imports><![CDATA[{imports_json}]]></add_imports>'''
    
    # Build the XML def file
    xml_content = f'''<?xml version="1.0" encoding="UTF-8"?>
<definition>
  <title>{escape_xml_value(construction_name)}</title>
  <author>Nexus Mod Member: @Tobilchiro wrote Secrets of Khazad-dum</author>
  <description>New Building Pieces from within the game and new creations</description>
  <mod file="Moria\\Content\\Tech\\Data\\Building\\DT_ConstructionRecipes.json">
    <add_row name="{escape_xml_value(construction_name)}"><![CDATA[{recipe_json}]]></add_row>
  </mod>
  <mod file="Moria\\Content\\Tech\\Data\\Building\\DT_Constructions.json">{imports_section}
    <add_row name="{escape_xml_value(construction_name)}"><![CDATA[{construction_json}]]></add_row>
  </mod>
</definition>
'''
    
    # Write the file
    output_path = output_dir / f"{construction_name}.def"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(xml_content)
    
    return output_path


def main():
    """Main entry point."""
    # Paths
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    test_dir = project_dir / 'test'
    
    recipes_file = test_dir / 'DT_ConstructionRecipes.json'
    constructions_file = test_dir / 'DT_Constructions.json'
    
    # Output directory in AppData
    output_dir = get_output_dir()
    
    print(f"Loading {recipes_file}...")
    recipes_data = load_json_file(recipes_file)
    recipes = recipes_data['Exports'][0]['Table']['Data']
    print(f"  Found {len(recipes)} recipes")
    
    print(f"Loading {constructions_file}...")
    constructions_data = load_json_file(constructions_file)
    constructions = constructions_data['Exports'][0]['Table']['Data']
    all_imports = constructions_data.get('Imports', [])
    print(f"  Found {len(constructions)} constructions")
    print(f"  Found {len(all_imports)} imports (icon references)")
    
    # Build lookup by name
    recipe_by_name = {r['Name']: r for r in recipes}
    construction_by_name = {c['Name']: c for c in constructions}
    
    # Generate def files for items that have both recipe and construction
    generated = 0
    skipped = 0
    
    for name in construction_by_name:
        if name in recipe_by_name:
            recipe = recipe_by_name[name]
            construction = construction_by_name[name]
            
            # Get icon import entries for this construction
            icon_index = get_icon_import_index(construction)
            icon_imports = get_import_entries_for_icon(icon_index, all_imports) if icon_index else []
            
            output_path = generate_def_file(name, recipe, construction, icon_imports, output_dir)
            generated += 1
            print(f"  Generated: {output_path.name}")
        else:
            print(f"  Skipped (no recipe): {name}")
            skipped += 1
    
    print(f"\nDone! Generated {generated} .def files, skipped {skipped}")
    print(f"Output directory: {output_dir}")


if __name__ == '__main__':
    main()
