"""
NameMap Analyzer Helper

Analyzes the NameMap structure in UAssetAPI JSON files to understand
what FName entries are stored and how they relate to Data content.

Key findings:
- NameMap is AUTO-GENERATED by UAssetAPI when serializing
- It contains: row names, material handles, tool handles, ore types
- It does NOT contain: enum values, property names (those are schema-defined)
- We do NOT need to store NameMap in .def files

Usage:
    python helpers/namemap_analyzer.py [json_file]
"""

import json
import sys
from pathlib import Path
from collections import defaultdict


def categorize_namemap(namemap: list) -> dict:
    """Categorize NameMap entries by type."""
    categories = defaultdict(list)
    
    for name in namemap:
        if name.startswith('Item.'):
            categories['Item Handles'].append(name)
        elif name.startswith('Consumable.'):
            categories['Consumable Handles'].append(name)
        elif name.startswith('Ore.'):
            categories['Ore Handles'].append(name)
        elif name.startswith('Tool.'):
            categories['Tool Handles'].append(name)
        elif name.startswith('CraftingStation'):
            categories['Crafting Stations'].append(name)
        elif name.startswith('/Game/'):
            categories['Asset Paths'].append(name)
        elif '.' in name and not name.startswith('E') and '::' not in name:
            categories['Other Handles'].append(name)
        elif '_' in name:
            categories['Row Names'].append(name)
        else:
            categories['Other'].append(name)
    
    return dict(categories)


def extract_names_from_data(data) -> set:
    """Recursively extract all string values that could be FNames from Data."""
    names = set()
    
    if isinstance(data, dict):
        # Row Name field
        if 'Name' in data and isinstance(data['Name'], str):
            val = data['Name']
            # Skip property names that are in schema
            if not val.startswith('b') or '_' in val:  # booleans start with 'b'
                names.add(val)
        
        # Handle Value fields (material IDs, etc.)
        if 'Value' in data and isinstance(data['Value'], str):
            val = data['Value']
            if not val.startswith('UAssetAPI') and '::' not in val:
                names.add(val)
        
        # Recurse into all values
        for v in data.values():
            names.update(extract_names_from_data(v))
    elif isinstance(data, list):
        for item in data:
            names.update(extract_names_from_data(item))
    
    return names


def analyze_file(json_path: Path):
    """Analyze a single JSON file's NameMap."""
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    filename = json_path.name
    print(f"\n{'='*60}")
    print(f"Analyzing: {filename}")
    print('='*60)
    
    # Get NameMap
    namemap = data.get('NameMap', [])
    print(f"\nNameMap entries: {len(namemap)}")
    
    # Categorize
    categories = categorize_namemap(namemap)
    print("\nCategories:")
    for cat, items in sorted(categories.items(), key=lambda x: -len(x[1])):
        unique = len(set(items))
        print(f"  {cat}: {len(items)} entries ({unique} unique)")
        if items[:3]:
            print(f"    Examples: {items[:3]}")
    
    # Check if Imports exist
    imports = data.get('Imports', [])
    if imports:
        print(f"\nImports: {len(imports)} entries")
        print("  (Icon/asset references - REQUIRED for reconstruction)")
    
    # Check Data
    try:
        table_data = data['Exports'][0]['Table']['Data']
        print(f"\nData entries: {len(table_data)}")
        
        # Extract and compare
        extracted = extract_names_from_data(table_data)
        namemap_set = set(namemap)
        
        only_namemap = namemap_set - extracted
        only_data = extracted - namemap_set
        
        print(f"\nNameMap vs Data comparison:")
        print(f"  In NameMap only: {len(only_namemap)}")
        print(f"  In Data only: {len(only_data)}")
        
    except (KeyError, IndexError):
        print("\nCould not parse Data structure")
    
    return {
        'file': filename,
        'namemap_count': len(namemap),
        'imports_count': len(imports),
        'categories': categories
    }


def main():
    if len(sys.argv) > 1:
        # Analyze specific file
        json_path = Path(sys.argv[1])
        if json_path.exists():
            analyze_file(json_path)
        else:
            print(f"File not found: {json_path}")
    else:
        # Analyze test files
        test_dir = Path(__file__).parent.parent / 'test'
        
        print("NameMap Analyzer")
        print("="*60)
        print("\nKey Insight: NameMap is AUTO-GENERATED by UAssetAPI")
        print("We do NOT need to store it in .def files!")
        print("\nWhat we DO need:")
        print("  - Data entries (the actual row content)")
        print("  - Imports (for DT_Constructions - icon references)")
        
        for json_file in sorted(test_dir.glob('*.json')):
            if 'modded' not in str(json_file):
                analyze_file(json_file)


if __name__ == '__main__':
    main()
